theme = "paperback"
BaseURL = "http://wadayama.github.io/public/"

title = "Taadshi Wadayama"
HomepagePosts = 3
pygmentsUseClasses = true

pygmentsCodefences = true

[params]
AuthorName = "Tadashi Wadayama"
